### PR TITLE
Modern icons for the wallet(Qt).

### PR DESCRIPTION
**Pull request by d4ndo**
Using awesome and raphaël font to create new icons.

http://fontawesome.io/icons/
http://icons.marekventur.com

### CODE REVIEW

**Comment by d4ndo** [comment]
Please wait with this Pullrequest. /src/qt/Makefile needs modification.

**Comment by d4ndo** [comment]
Modified the Makefile and replaced the »spinner«, »connection« and »tx« icons. Added a new label »logo« that can be set by stylesheet(theme).
P.S. A new theme is in work.

**Comment by d4ndo** [comment]
The chaincoin community still needs to test the changes.

**Comment by rolichain** [comment]
Thanks, the two sources you mentioned appear to be MIT license friendly, so that's good.

**Comment by d4ndo** [comment]
I had to undo some stuff. The changes made did not compile as they should, because of some Qt-Plugins. I tried to move to svg icons, that also require the SVG Qt Plugin. So all we have won are the modern icon theme. 

Maybe you could provide another test client for the community. If no complains pop up we could continue.

**Pull request merged**
