### PR TITLE
v12.2 update

### PR DESCRIPTION
**Pull request by howardfinter**
This pull request will replace all existing files for v0.9.3.x.
There appears to be a bug in the options dialog that doesn't update the settings to show masternodes. I will fix this and do another pull request. It would be good to get others testing this  version as soon as possible on the testnet. All updates going forward should have peer review before being merged.

Credits go to pcre, d4ndo & Hash for most of the changes being merge here. I have reviewed all code line by line to the best of my ability. The proof of work & subsidy follow the existing chaincoin codebase. The MN payouts have been changed to account for governance and should be tested to confirm it is working as expected. There are chainparams settings that need to be defined. We can determine these settings as we create a roll-out strategy.

-Samps

### CODE REVIEW

**Comment by suprnurd** [comment]
@howardfinter How are there merge conflicts?

**Comment by suprnurd** [comment]
I don't understand the thought process here... are you for real??

**Comment by howardfinter** [comment]
Basically v0.12.0 will replace all the existing code. If you want to track the changes to v0.12 we would need to fork dash in your repo and then do another pull request with our changes. That would be the better option. Otherwise, it will be impossible to track all the changes we made to migrate. What are your thoughts?On Dec 4, 2017 9:38 PM, Alan Rudolf <notifications@github.com> wrote:I don't understand the thought process here... are you for real??

**Comment by howardfinter** [comment]
Otherwise, I can attempt to do a merge and resolve all the conflicts. That just seems overkill since there are so many conflicts between the two codebases. I will do that if you prefer it. I just think there is a lot of room for error.Let me know what you are most comfortable with.On Dec 4, 2017 9:53 PM, Michael  wrote:Basically v0.12.0 will replace all the existing code. If you want to track the changes to v0.12 we would need to fork dash in your repo and then do another pull request with our changes. That would be the better option. Otherwise, it will be impossible to track all the changes we made to migrate. What are your thoughts?On Dec 4, 2017 9:38 PM, Alan Rudolf <notifications@github.com> wrote:I don't understand the thought process here... are you for real??

**Comment by suprnurd** [comment]
I think we should have preserved all of the individual commits from the source repos that would have made it easier to see what has been changed and also make reviewing the code much easier.

**Comment by howardfinter** [comment]
Let me fix it and do another pull request.

**Comment by suprnurd** [comment]
This was really sad to have to do. I'm ashamed at myself.

**Comment by pewilliams71** [comment]
No need to feel that way Alan.  This is a pragmatic action.  Oversight by the communty continues.
Pete (fellowserf)

**Comment by suprnurd** [comment]
I was referring to actually accepting a pull request like this.

**Comment by suprnurd** [comment]
@howardfinter Still waiting on you to re-fork the Chaincoin repo and make the community changes to the 0.12.X branch.

**Comment by howardfinter** [comment]
I will do that tonight.

**Comment by suprnurd** [comment]
Awesome!!

**Pull request merged**
